# image: https://container-registry.oracle.com/ords/f?p=113:10::::::
# docs: http://docs.oracle.com/en/database/

version: '3.8'

services:
  oracleex:
    image: container-registry.oracle.com/database/express:${APP_VERSION}
    container_name: ${APP_NAME}  
    environment:
      - ORACLE_PWD
      - ORACLE_CHARACTERSET
    volumes:
      - data:/opt/oracle/oradata
      - startup:/opt/oracle/scripts/startup
      - setup:/opt/oracle/scripts/setup 
    ports:
      -  ${APP_DB_PORT}:1521
      -  ${APP_EM_PORT}:5500
    restart: always
    profiles:
      - express

  oracle:
    image: container-registry.oracle.com/database/enterprise:${APP_VERSION}
    container_name: ${APP_NAME}  
    environment:
      - ORACLE_SID
      - ORACLE_PDB
      - ORACLE_PWD
      - INIT_SGA_SIZE
      - INIT_PGA_SIZE
      - ORACLE_EDITION
      - ORACLE_CHARACTERSET
      - ENABLE_ARCHIVELOG
    volumes:
      - data:/opt/oracle/oradata
      - startup:/opt/oracle/scripts/startup
      - setup:/opt/oracle/scripts/setup 
    ports:
      -  ${APP_DB_PORT}:1521
      -  ${APP_EM_PORT}:5500
    restart: always
    profiles:
      - enterprise
      - standard


networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  data:
  startup:
  setup:
